CREATE (a1:Red {name:'A1'}), (a2:Red {name:'A2'}),
       (b1 {name:'B1'}), (b2:Green {name:'B2'}), (b3 {name:'B3'}),
       (c1:Green {name:'C1'}), (c2:Green {name:'C2'}), (c3:Green {name:'C3'}), (c4 {name:'C4'}),
       (a1)-[:RELATED]->(a2),
       (a1)-[:RELATED]->(b1),
       (a1)-[:RELATED]->(b2),
       (a1)-[:RELATED]->(b3),
       (a2)-[:RELATED]->(b2),
       (a2)-[:RELATED]->(c4),
       (b1)-[:RELATED]->(b2),
       (b1)-[:RELATED]->(c1),
       (b1)-[:RELATED]->(c2),
       (b1)-[:RELATED]->(c3),
       (b2)-[:RELATED]->(c2),
       (b2)-[:RELATED]->(c4),
       (b3)-[:RELATED]->(c1);
