
create
       (s1:Stop {id: 'S1', minTransferTime:duration('P0M0DT1M')}),
       (s2:Stop {id: 'S2', minTransferTime:duration('P0M0DT1M')}),
       (s3:Stop {id: 'S3', minTransferTime:duration('P0M0DT1M')}),
       (s4:Stop {id: 'S4', minTransferTime:duration('P0M0DT1M')}),
       (s5:Stop {id: 'S5', minTransferTime:duration('P0M0DT1M')}),

       (r1:Route:RUNS_6:RUNS_7 {shortName:'S1 -> S3'}),
       (t1:Trip)-[:USES]->(r1),
       (sp11:StopTime {arrivalOffset:duration('P0M0DT500M'), departureOffset:duration('P0M0DT500M')}),
       (sp12:StopTime {arrivalOffset:duration('P0M0DT509M'), departureOffset:duration('P0M0DT510M')}),
       (sp13:StopTime {arrivalOffset:duration('P0M0DT519M'), departureOffset:duration('P0M0DT520M')}),
       (sp11)-[:STOPS_AT]->(s1),
       (sp12)-[:STOPS_AT]->(s2),
       (sp13)-[:STOPS_AT]->(s3),
       (sp11)-[:NEXT_STOP]->(sp12),
       (sp12)-[:NEXT_STOP]->(sp13),
       (sp11)-[:BELONGS_TO]->(t1),
       (sp12)-[:BELONGS_TO]->(t1),
       (sp13)-[:BELONGS_TO]->(t1),

       (r2:Route:RUNS_6:RUNS_7 {shortName:'S3 -> S4'}),
       (t2:Trip)-[:USES]->(r2),
       (sp21:StopTime {arrivalOffset:duration('P0M0DT530M'), departureOffset:duration('P0M0DT530M')}),
       (sp22:StopTime {arrivalOffset:duration('P0M0DT539M'), departureOffset:duration('P0M0DT540M')}),
       (sp21)-[:STOPS_AT]->(s3),
       (sp22)-[:STOPS_AT]->(s4),
       (sp21)-[:NEXT_STOP]->(sp22),
       (sp21)-[:BELONGS_TO]->(t2),
       (sp22)-[:BELONGS_TO]->(t2),

       (r3:Route:RUNS_6:RUNS_7 {shortName:'direct route'}),
       (t3:Trip)-[:USES]->(r3),
       (sp31:StopTime {arrivalOffset:duration('P0M0DT510M'), departureOffset:duration('P0M0DT510M')}),
       (sp32:StopTime {arrivalOffset:duration('P0M0DT519M'), departureOffset:duration('P0M0DT520M')}),
       (sp33:StopTime {arrivalOffset:duration('P0M0DT529M'), departureOffset:duration('P0M0DT530M')}),
       (sp34:StopTime {arrivalOffset:duration('P0M0DT539M'), departureOffset:duration('P0M0DT540M')}),
       (sp35:StopTime {arrivalOffset:duration('P0M0DT549M'), departureOffset:duration('P0M0DT550M')}),
       (sp31)-[:STOPS_AT]->(s1),
       (sp32)-[:STOPS_AT]->(s2),
       (sp33)-[:STOPS_AT]->(s3),
       (sp34)-[:STOPS_AT]->(s4),
       (sp35)-[:STOPS_AT]->(s5),
       (sp31)-[:NEXT_STOP]->(sp32),
       (sp32)-[:NEXT_STOP]->(sp33),
       (sp33)-[:NEXT_STOP]->(sp34),
       (sp34)-[:NEXT_STOP]->(sp35),
       (sp31)-[:BELONGS_TO]->(t3),
       (sp32)-[:BELONGS_TO]->(t3),
       (sp33)-[:BELONGS_TO]->(t3),
       (sp34)-[:BELONGS_TO]->(t3),
       (sp35)-[:BELONGS_TO]->(t3),

       (r4:Route:RUNS_1:RUNS_2:RUNS_3:RUNS_4:RUNS_5 {shortName:'wrong day'}),
       (t4:Trip)-[:USES]->(r4),
       (sp41:StopTime {arrivalOffset:duration('P0M0DT530M'), departureOffset:duration('P0M0DT530M')}),
       (sp42:StopTime {arrivalOffset:duration('P0M0DT539M'), departureOffset:duration('P0M0DT540M')}),
       (sp41)-[:STOPS_AT]->(s1),
       (sp42)-[:STOPS_AT]->(s4),
       (sp41)-[:NEXT_STOP]->(sp42),
       (sp41)-[:BELONGS_TO]->(t4),
       (sp42)-[:BELONGS_TO]->(t4),

       (r5:Route:RUNS_6{shortName:'double back'}),
       (t5:Trip)-[:USES]->(r5),
       (sp51:StopTime {arrivalOffset:duration('P0M0DT530M'), departureOffset:duration('P0M0DT530M')}),
       (sp52:StopTime {arrivalOffset:duration('P0M0DT539M'), departureOffset:duration('P0M0DT540M')}),
       (sp53:StopTime {arrivalOffset:duration('P0M0DT530M'), departureOffset:duration('P0M0DT530M')}),
       (sp51)-[:STOPS_AT]->(s3),
       (sp52)-[:STOPS_AT]->(s2),
       (sp53)-[:STOPS_AT]->(s4),
       (sp51)-[:NEXT_STOP]->(sp52),
       (sp52)-[:NEXT_STOP]->(sp53),
       (sp51)-[:BELONGS_TO]->(t5),
       (sp52)-[:BELONGS_TO]->(t5),
       (sp53)-[:BELONGS_TO]->(t5)
